name: flutter_gofast
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #Firebase
  google_sign_in: ^4.4.4
  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.5
  #Local Storate
  shared_preferences: ^0.5.7
  #Http request
  dio: ^3.0.9
  #Gerencia de Estado
  flutter_mobx: ^1.1.0
  mobx: ^1.1.1
  #Rotas, Injecao de Dependencia
  flutter_modular: ^1.1.2
  #Icones https://feathericons.com/
  flutter_icons: ^1.1.0
  #Localizacao e idioma
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  mockito: ^4.1.1
  mobx_codegen: ^1.0.3
  build_runner: ^1.9.0
  effective_dart: ^1.2.1
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lang/
    - assets/images/

  fonts:
    - family: Google
      fonts: 
        - asset: assets/fonts/ProductSans-Regular.ttf
        - asset: assets/fonts/ProductSans-Bold.ttf
          weight: 700
